//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyVentas_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VentasLeonEntities : DbContext
    {
        public VentasLeonEntities()
            : base("name=VentasLeonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Abastecimiento> Tb_Abastecimiento { get; set; }
        public virtual DbSet<Tb_Categoria> Tb_Categoria { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Detalle_Compra> Tb_Detalle_Compra { get; set; }
        public virtual DbSet<Tb_Detalle_Factura> Tb_Detalle_Factura { get; set; }
        public virtual DbSet<Tb_Factura> Tb_Factura { get; set; }
        public virtual DbSet<Tb_Orden_Compra> Tb_Orden_Compra { get; set; }
        public virtual DbSet<Tb_Producto> Tb_Producto { get; set; }
        public virtual DbSet<Tb_Proveedor> Tb_Proveedor { get; set; }
        public virtual DbSet<Tb_RepositorioDocumentos> Tb_RepositorioDocumentos { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_UnidadMedida> Tb_UnidadMedida { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<Tb_Vendedor> Tb_Vendedor { get; set; }
    
        public virtual int usp_DeudaCliente(string vcod, ObjectParameter vdeuda)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeudaCliente", vcodParameter, vdeuda);
        }
    
        public virtual ObjectResult<usp_VentasPorAño_Result> usp_VentasPorAño()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_VentasPorAño_Result>("usp_VentasPorAño");
        }
    
        public virtual ObjectResult<usp_ListarProductosProveedor_Result> usp_ListarProductosProveedor(string cod_prv)
        {
            var cod_prvParameter = cod_prv != null ?
                new ObjectParameter("cod_prv", cod_prv) :
                new ObjectParameter("cod_prv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarProductosProveedor_Result>("usp_ListarProductosProveedor", cod_prvParameter);
        }
    
        public virtual ObjectResult<usp_ListarFacturas_Paginacion_Result> usp_ListarFacturas_Paginacion(string cod_cli, string cod_ven, string estado, Nullable<int> numPag)
        {
            var cod_cliParameter = cod_cli != null ?
                new ObjectParameter("Cod_cli", cod_cli) :
                new ObjectParameter("Cod_cli", typeof(string));
    
            var cod_venParameter = cod_ven != null ?
                new ObjectParameter("Cod_ven", cod_ven) :
                new ObjectParameter("Cod_ven", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var numPagParameter = numPag.HasValue ?
                new ObjectParameter("NumPag", numPag) :
                new ObjectParameter("NumPag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarFacturas_Paginacion_Result>("usp_ListarFacturas_Paginacion", cod_cliParameter, cod_venParameter, estadoParameter, numPagParameter);
        }
    
        public virtual int usp_NumPag_ListarFacturas_Paginacion(string cod_cli, string cod_ven, string estado, ObjectParameter nUMREG)
        {
            var cod_cliParameter = cod_cli != null ?
                new ObjectParameter("Cod_cli", cod_cli) :
                new ObjectParameter("Cod_cli", typeof(string));
    
            var cod_venParameter = cod_ven != null ?
                new ObjectParameter("Cod_ven", cod_ven) :
                new ObjectParameter("Cod_ven", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_NumPag_ListarFacturas_Paginacion", cod_cliParameter, cod_venParameter, estadoParameter, nUMREG);
        }
    }
}
